designatuci/DUCI-website

jsconfig.json, src/app/App.js, src/app/Symbols.js, src/app/components/EmailForm/EmailForm.js, src/app/components/Footer/Footer.js, src/app/components/Nav/Nav.js, src/app/components/Text/Text.js, src/app/pages/About/About.js, src/app/pages/About/components/Profile/Profile.js, src/app/pages/Brand/Brand.js, src/app/pages/Contact/Contact.js, src/app/pages/Designathons.js, src/app/pages/Events/Events.js, src/app/pages/Events/EventsAll.js, src/app/pages/Events/components/EventCard/EventCard.js, src/app/pages/Hey.js, src/app/pages/Home/Home.js, src/app/pages/Join/Join.js, src/app/pages/Merch/Merch.js, src/app/pages/Merch/components/MerchDropListing/MerchDropListing.js, src/app/pages/Merch/components/MerchItem/MerchItem.js, src/app/pages/Merch/pages/Shirt22/Shirt22.js, src/app/pages/NotFound/NotFound.js, src/app/pages/PT/PT.js, src/app/pages/Resources/Resources.js, src/app/pages/ResourcesFeatured/ResourcesFeatured.js
Changed imports to absolute paths and reordered imports.
Might eventually add an eslint configuration with import/order rules.
Currently working on extracting components in `Symbols.js` and also reorganizing static assets from `public` to `src`.
=> Configure absolute imports and clean up imports

package-lock.json, package.json, public/index.html, src/app/components/Footer/Footer.js
Not really utilizing GA. Talked offline with dev team to remove it
=> Remove GA for plausible

src/assets/data/events/all.json
Uploaded first event of the quarter
=> Updated New Event

src/assets/data/currentBoard.json, src/assets/data/events/all.json
Changed my board info as well as added 2 new events - one still needs details finalized.
Tested on variety of resolutions without any issues.
=> Updated events and board info

src/assets/data/events/all.json
Updated 1/23 gaming industry event 
I tested how the web page looks on every screen size to ensure it is still responsive. I clicked on the zoom link to ensure it works
=> Updated new gaming industry event

src/app/pages/Designathons/Designathon23/components/SectionNavigation/index.jsx, src/app/pages/Designathons/Designathon23/index.js
=> Remove imports and sponsors clickable

src/app/App.js, src/app/components/Banner/Banner.js, src/app/components/Banner/Banner.module.scss, src/app/components/Banner/index.js, src/app/components/Nav/Nav.js, src/app/components/Nav/Nav.scss, src/app/components/index.js, src/app/styles/colors.scss
As requested by Meghna, create a banner at the top of our site linking to the board applications.
=> Add recruitment banner

src/app/App.js, src/app/pages/PT/PT.js
- Update registration form link and deadline for Fall 2023
- Update description of Project Team and include meeting times
- Hide Join Us link while applications are open
Closes #47.
=> Update Project Teams page with Fall 2023 info

src/app/pages/Houses/Houses.jsx, src/app/pages/Houses/Houses.module.scss, src/app/pages/Houses/useHousePoints.js
Dynamically fetch house points data from Google Sheets to display together with each house.
These will be automatically updated when the points sheet is updated by our board members.
=> Display house points values from Google Sheets

src/assets/data/events/all.json
1. Adds description to "Dissecting Design Systems" in `events/all.json`
=> chore: update event description

src/app/pages/Designathons/Designathon24/Designathon24.js, src/app/pages/Designathons/Designathon24/components/Notecard/Notecard.jsx, src/app/pages/Designathons/Designathon24/components/Speakers/Speakers.jsx
=> chore: remove unused imports

src/app/pages/Designathons/Designathon24/components/About/About.module.scss, src/app/pages/Designathons/Designathon24/components/Polaroid/Polaroid.module.scss, src/app/pages/Designathons/Designathon24/components/Rules/Rules.module.scss
1. Went through and added pointer-events: none to all the graphics on the page
=> style: set pointer-events: none for graphics

src/app/pages/Designathons/Designathon24/components/Schedule/Schedule.module.scss, src/app/pages/Designathons/Designathon24/components/Schedule/index.jsx
1. Update Sunday events
2. Adjust styling
3. Add date toggle
=> feat: update schedule pt.2

src/app/pages/Designathons/Designathon24/components/FAQ/FAQ.module.scss, src/app/pages/Designathons/Designathon24/components/FAQ/index.jsx, src/app/pages/Designathons/Designathon24/components/SectionNavigation/index.jsx
1. Update text according to the website text doc
2. Fix minor styling issue
3. Merged main, fixed build issue (unused var)
=> feat: update faq text

src/app/pages/Designathons/Designathon24/Designathon24.module.scss, src/app/pages/Designathons/Designathon24/components/About/index.jsx
1. `overflow: clip;` at the root
Might be a tad heavy handed, but it works (I think).
=> feat: add overflow: clip to des24 root

src/app/pages/Designathons/Designathon24/components/Speakers/Speakers.module.scss
1. Tweaked the css and made smaller screens one column
=> style: speaker section responsiveness

src/app/pages/Designathons/Designathon24/components/Splash/Splash.jsx
1. Update the time on the splash to `May 17th 5:00 PM - May 19th 6:00 PM`
=> chore: update splash time

src/app/pages/Designathons/Designathon24/components/Schedule/index.jsx
=> chore: update schedule

src/app/pages/Designathons/Designathon24/components/FAQ/FAQ.module.scss, src/app/pages/Designathons/Designathon24/components/Prizes/Prizes.module.scss, src/app/pages/Designathons/Designathon24/components/Splash/Splash.jsx, src/app/pages/Designathons/Designathon24/components/Splash/Splash.module.scss, src/app/pages/Designathons/Designathon24/components/Sponsors/Sponsors.module.scss
1. Add position relative to landing page elements
2. Add pointer events none to new graphics
=> fix: correct styling, pointer events none

src/app/pages/Designathons/Designathon24/assets/data/rules.json
1. One-liner updating rule one as Elise requested: 
`"All members of your team must be a current undergraduate OR graduate student with an associated institutional (.edu) email"`
=> chore: update rule 1

src/app/pages/Designathons/Designathon24/components/Prizes/index.jsx
1. Update prizes according to Elise's request:
Requested:
PR:
=> chore: update prizes

src/app/pages/Designathons/Designathon24/components/Splash/Splash.jsx, src/app/pages/Designathons/Designathon24/components/Splash/Splash.module.scss
1. Add ~~volunteer~~ (future) and mentor links to the splash
2. Simplify dates on the splash (remove specific hours)
=> feat: setup mentor links

src/app/pages/Designathons/Designathon24/components/Splash/Splash.jsx, src/app/pages/Designathons/Designathon24/components/Splash/Splash.module.scss
1. Add in button with the volunteer link
=> feat: add volunteer button

src/app/pages/Designathons/Designathon24/assets/data/judges.json
1. Update position to: `Head of UX Design & Research @ SAP`
=> chore: update marga's position

src/app/pages/Designathons/Designathon24/components/Schedule/Schedule.module.scss, src/app/pages/Designathons/Designathon24/components/Schedule/index.jsx
1. Update text as shown here: https://docs.google.com/spreadsheets/d/1zdlt4gqnaa_sUxGC28lC9xGQXiryulUf3WuxdS0qVk8/edit#gid=1669677419
2. Add styling to host names
=> chore: update final schedule text

src/assets/data/events/all.json
1. Added event for `Cross-Collaboration Between Researcher and Designer`
=> chore: add event

src/app/pages/Designathons/Designathon24/components/Splash/Splash.jsx, src/app/pages/Designathons/Designathon24/components/Splash/Splash.module.scss
1. Remove mentor, participant, volunteer buttons
=> chore: remove signup buttons

src/app/pages/Designathons/Designathon24/assets/data/rules.json, src/app/pages/Designathons/Designathon24/components/Rules/Rules.jsx, src/app/pages/Designathons/Designathon24/components/Splash/Splash.module.scss
1. Add rule 8: `Teams must be compromised of entirely online or entirely in-person participants.`
=> feat: add rule 8
